# Matrix Operations with Scalars and Vectors

__Purpose:__ The purpose of this lecture is to expand our Linear Algebra knowledge to work with matrices and perform matrix operations with scalars and vectors.  

__At the end of this lecture you will be able to:__
> 1. Understand matrix operations with scalars
> 2. Understand matrix operations with vectors

### 1.1.1 Mathematical Operations with Matrices and Scalars

__Overview:__
- Addition and multiplication of a matrix by a scalar is very straightforward:
> 1. __Addition:__ When adding a scalar to the matrix, each element is added by the scalar value - this operation is performed on an "element-by-element" fashion: $\alpha + \pmb A$ = $\alpha + [\pmb A_{i,j}]$
> 2. __Multiplication:__ When multiplying a scalar to the matrix, each element is multiplied by the scalar value - this operation is performed on an "element-by-element" fashion: $\alpha \pmb A$ = $\alpha*[\pmb A_{i,j}]$

__Helpful Points:__
1. Matrices act the same as vectors do when they are multiplied by and added with scalars (that is, the scalar is applied on an element-by-element basis) 

__Practice:__ Examples of Mathematical Operations with Matrices and Scalars in Python 

In [1]:
import numpy as np 
from scipy import linalg 
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
%matplotlib inline 

### Example 1 (Addition):

In [2]:
alpha = 2
mat = np.array([[1,1,2],[4,5,6]])
print(mat)

[[1 1 2]
 [4 5 6]]


In [3]:
mat_addition = alpha + mat
print(mat_addition)

[[3 3 4]
 [6 7 8]]


### Example 2 (Multiplication):

In [4]:
mat_multiplication = alpha * mat
print(mat_multiplication)

[[ 2  2  4]
 [ 8 10 12]]


### 1.1.2 Mathematical Operations with Matrices and Vectors 

__Overview:__
- It is also possible to add and multiply a matrix by a vector:
> 1. __Addition:__ If $\pmb A$ is an $m$ $x$ $n$ matrix and $\pmb u$ is a vector, then to add the vector to the matrix, simply add the vector to each row of the matrix. 
<center> $\pmb C_{ij} = \pmb A_{ij} + b_j$ </center>

> 2. __Multiplication:__ If $\pmb A$ is an $m$ $x$ $n$ matrix with columns $\pmb A_1$, $\pmb A_2$, $\pmb A_3$, ...,  $\pmb A_n$ and $\pmb u$ is a vector of size n, then the matrix-vector product is simply a linear combination of the elements in $\pmb u$ with the columns in $\pmb A$:

\begin{equation}
\begin{bmatrix}
    A_{11}       & A_{12} & A_{13} & \dots & A_{1n} \\
    A_{21}       & A_{22} & A_{23} & \dots & A_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    A_{m1}       & A_{m2} & A_{m3} & \dots & A_{mn}
\end{bmatrix}
\begin{bmatrix}
    u_1 \\
    u_2 \\
    u_3 \\
    \vdots \\
    u_n
\end{bmatrix}
=
\begin{bmatrix}
    A_{11}u_1 + A_{12}u_2 + A_{13}u_3 + \dots + A_{1n}u_n \\
    A_{21}u_1 + A_{22}u_2 + A_{23}u_3 + \dots + A_{2n}u_n \\
    \vdots \\
    A_{m1}u_1 + A_{m2}u_2 + A_{m3}u_3 + \dots + A_{mn}u_n \\
\end{bmatrix}
\end{equation}

\begin{equation}
\begin{bmatrix}
    \pmb A_1 & \pmb A_2 & \pmb A_3 & \dots & \pmb A_n
\end{bmatrix}
\begin{bmatrix}
    u_1 \\
    u_2 \\
    u_3 \\
    \vdots \\
    u_n
\end{bmatrix}
=
\begin{bmatrix}
    u_1\pmb A_1 + u_2\pmb A_2 + u_3\pmb A_3 + \dots + u_n\pmb A_n
\end{bmatrix}
\end{equation}

<center>$\pmb A \pmb u = u_1 \pmb A_1 + u_2 \pmb A_2 + u_3 \pmb A_3 + ... + u_n \pmb A_n$</center>
    
__Helpful Points:__
1. The most important rule to follow when adding or multiplying a matrix by a vector is to remember that the vector must have the same number of elements (`n`) as there are columns in the matrix, otherwise you can't add or multiply that vector 
2. The result of a matrix-vector product is a vector 
3. Recall linear combination definition 

__Practice:__ Examples of Matrix-Vector Product in Python 

### Example 1 (Addition):

### Example 1.1 (Broadcastable Arrays):

In [5]:
my_vector = np.array([1,2,3])
print(my_vector)
my_matrix = np.array([[0,1,0], [2,2,1], [3,3,3]])
print(my_matrix)

[1 2 3]
[[0 1 0]
 [2 2 1]
 [3 3 3]]


In [6]:
my_vector.shape

(3,)

In [7]:
my_matrix.shape

(3, 3)

In [8]:
my_vector + my_matrix # "added vector to a matrix !"

array([[1, 3, 3],
       [3, 4, 4],
       [4, 5, 6]])

According to the broadcasting rules, the vector is first prepended with 1s such that the shape is the same as the matrix - (1,3) and (3,3). Then moving from right to left, the rules dictate that the resulting object will have the length equal to the larger of the two lengths, thus the resulting shape is (3,3).

### Example 1.2 (Non-Broadcastable Arrays):

In [10]:
my_vector = np.array([1,2])
print(my_vector)
my_matrix = np.array([[0,1,0], [2,2,1], [3,3,3]])
print(my_matrix)

[1 2]
[[0 1 0]
 [2 2 1]
 [3 3 3]]


In [11]:
my_vector.shape

(2,)

In [13]:
my_matrix.shape

(3, 3)

In [14]:
my_vector + my_matrix # "cannot add because of dimensions"

ValueError: operands could not be broadcast together with shapes (2,) (3,3) 

According to the broadcasting rules, the vector is first prepended with 1s such that the shape is the same as the matrix - (1,2) and (3,3). Then moving from right to left, the rules dictate that "2" and "3" can not be reconciled, since they have to be the either the same or one of the two has to be a "1". 

### Example 2 (Multiplication):

In [15]:
my_vector = np.array([1,2,3])
print(my_vector)
my_matrix = np.array([[0,1,0], [2,2,1], [3,3,3]])
print(my_matrix)

[1 2 3]
[[0 1 0]
 [2 2 1]
 [3 3 3]]


### Example 2.1 (Method 1 - With Dot Function):

In [16]:
np.dot(my_matrix,my_vector) # "firt element is 0*1+1*2+0*3"

array([ 2,  9, 18])

### Problem 1 

Create a vector $\pmb u = [1,1,0]$ and a matrix 

\begin{equation}
\pmb A = 
\begin{bmatrix}
    1 & 2 & 4\\
    2 & 0 & 1\\
\end{bmatrix}
\end{equation}

Perform vector-matrix multiplication using manual calculation on pencil and paper and also using the dot product function. **Find A.u**

In [ ]:
# write your code here 





### SOLUTION

### Problem 1 

Create a vector $\pmb u = [1,1,0]$ and a matrix 

\begin{equation}
\pmb A = 
\begin{bmatrix}
    1 & 2 & 4\\
    2 & 0 & 1\\
\end{bmatrix}
\end{equation}

Perform vector-matrix multiplication using manual calculation on pencil and paper and also using the dot product function.

In [ ]:
u = np.array([1,1,0])
A = np.array([[1,2,4],[2,0,1]])
print(u)
print(A)

In [ ]:
np.dot(A,u)