# Exercises: Numpy Arrays

In [1]:
import numpy as np
print(np.__version__)

1.19.4


## Create a vector consisting of 10 zeros

In [2]:
Z = np.zeros(10)

## Set the 5th value to 5

In [3]:
Z[4] = 5

## Create a vector with values ranging from 37 to 84

In [4]:
X = np.arange(37, 85)
X

array([37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84])

## Reverse that vector

In [5]:
X = X[::-1]
X

array([84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68,
       67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51,
       50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37])

## Create a 4x4 matrix with values ranging from 43 to 58 

In [6]:
H = np.arange(43, 59).reshape(4,4)
H

array([[43, 44, 45, 46],
       [47, 48, 49, 50],
       [51, 52, 53, 54],
       [55, 56, 57, 58]])

## Find the indices of nonzero elements in [0, 2, 7, 0, 0, 8, 0]

In [7]:
nz = np.nonzero([0,2,7,0,0,8,0])
print(nz)

(array([1, 2, 5]),)


## Create a 3x3 identity matrix

In [8]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Create a 2x4x3 array of random values

In [9]:
Z = np.random.random((2,4,3))
print(Z)

[[[0.40013795 0.58557086 0.09569945]
  [0.40059908 0.93620048 0.89181528]
  [0.13161526 0.65817358 0.74227169]
  [0.25245703 0.12344601 0.01266493]]

 [[0.00293034 0.55560592 0.54230361]
  [0.75036039 0.73847699 0.97275494]
  [0.04406004 0.0989886  0.56385112]
  [0.92729138 0.14495096 0.38043376]]]


## Find the min, max, and mean values of that array

In [10]:
print(Z.min(), Z.max(), Z.mean())

0.002930343741570529 0.9727549428214862 0.45636082054542665


## Create a 7x7 array with 1's on the border and 0's inside

In [11]:
Z = np.ones((7,7))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


## Add a border (filled with 0's) around that array
Hint: use the `pad()` method of the array.

In [12]:
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Normalize a 5x5 random matrix
That is, subtract the matrix mean from each value and then divide the result by the matrix standard deviation.

In [13]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.74580416 -0.07741962 -1.7228219   1.82049325 -1.42480604]
 [ 0.48114857 -0.12728185 -0.13828717  1.15072029 -0.59666884]
 [ 0.1093492  -0.17347318 -1.44911031  1.42187619  0.3791256 ]
 [ 1.35298787  0.59437059  0.59357517 -1.71540159  0.02314738]
 [-1.32010133  1.36155204  0.51264734 -0.64701978  0.3372023 ]]


## Multiply a 5x3 matrix of ones by a 3x2 matrix of twos
(i.e., take the dot product)

In [14]:
Z = np.dot(np.ones((5,3)), np.ones((3,2))*2)
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))*2

[[6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]]


## Construct two arrays of 12 random integers from 0 to 9

In [15]:
Z1 = np.random.randint(0,10,12)
Z2 = np.random.randint(0,10,12)

## Find the common values between these two arrays
That is, values that appear in both arrays. They don't have to be in the same position.

In [16]:
print(np.intersect1d(Z1,Z2))

[0 4 5 9]


## Print the dates of yesterday, today, and tomorrow

In [17]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2020-12-16 2020-12-17 2020-12-18


## Create a vector of 10 sorted random values

In [18]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00260013 0.10203366 0.14051885 0.16214079 0.25403083 0.26196385
 0.28053166 0.28376211 0.33504764 0.34741503]


## Create random vector of size 10; replace the max value by 0
(Hint: use the `argmax` method.)

In [19]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.18322544 0.45453402 0.51550875 0.52445619 0.24097089 0.01847132
 0.49308339 0.         0.69805474 0.37623377]


# For more practice, 
check out this [100 numpy exercises (with solutions) repo on GitHub](https://github.com/rougier/numpy-100).